const CONFERENCES = [
  {
    id: "aom2026",
    short: "AOM 2026",
    name: "Academy of Management Annual Meeting",
    url: "https://aom.org/events/annual-meeting",
    deadline: "2026-01-13",
    conference_start: "2026-07-31",
    conference_end: "2026-08-04",
    location: "Philadelphia, PA, USA",
    topics: ["MGT","OB","ENT","STR","HR"],
    ranking: ["A*","A","B"],
    note: "Submission center opens early December"
  },
  {
    id: "aaahq2026",
    short: "AAA 2026",
    name: "American Accounting Association Annual Meeting",
    url: "https://aaahq.org/Meetings/Annual-Meeting",
    deadline: "2026-05-13",
    conference_start: "2026-08-02",
    conference_end: "2026-08-06",
    location: "Las Vegas, NV, USA",
    topics: ["ACC"],
    ranking: ["A*","A","B"],
    note: "Multiple submission windows; main paper deadline ~Feb 9"
  },
  {
    id: "afa2027",
    short: "AFA 2027",
    name: "American Finance Association Annual Meeting",
    url: "https://afajof.org/afa-meetings/",
    deadline: "2026-03-16",
    conference_start: "2027-01-03",
    conference_end: "2027-01-05",
    location: "Washington, DC, USA",
    topics: ["FIN"],
    ranking: ["A*"],
    note: "Submission fee required; AFA membership needed"
  },
  {
    id: "icis2026",
    short: "ICIS 2026",
    name: "International Conference on Information Systems",
    url: "https://icis2026.aisconferences.org/",
    deadline: "2026-05-01",
    conference_start: "2026-12-13",
    conference_end: "2026-12-16",
    location: "Lisbon, Portugal",
    topics: ["IS","TECH"],
    ranking: ["A*","A","B"],
    note: "Most competitive IS conference; ~70% rejection rate"
  },
  {
    id: "ecis2026",
    short: "ECIS 2026",
    name: "European Conference on Information Systems",
    url: "https://ecis2026.it/",
    deadline: "2025-11-15",
    conference_start: "2026-06-11",
    conference_end: "2026-06-17",
    location: "Milan, Italy",
    topics: ["IS","TECH"],
    ranking: ["A","B"],
    note: "AIS Region 2 flagship conference"
  },
  {
    id: "poms2026",
    short: "POMS 2026",
    name: "POMS Annual Conference",
    url: "https://pomsmeetings.org/conf-2026/",
    deadline: "2025-12-03",
    conference_start: "2026-05-07",
    conference_end: "2026-05-11",
    location: "Reno, NV, USA",
    topics: ["OPS","SCM"],
    ranking: ["A*","A"],
    note: "Abstract submission only (50 words)"
  },
  {
    id: "informs2026",
    short: "INFORMS 2026",
    name: "INFORMS Annual Meeting",
    url: "https://meetings.informs.org/wordpress/annual/",
    deadline: "2026-05-15",
    conference_start: "2026-11-01",
    conference_end: "2026-11-04",
    location: "San Francisco, CA, USA",
    topics: ["OPS","DS","SCM","IS"],
    ranking: ["A*","A","B"],
    note: "Abstract submission; speakers must register by July 22"
  },
  {
    id: "fma2026",
    short: "FMA 2026",
    name: "Financial Management Association Annual Meeting",
    url: "https://fma.org/fma-annual-meeting/",
    deadline: "2026-04-01",
    conference_start: "2026-10-14",
    conference_end: "2026-10-17",
    location: "Tampa, FL, USA",
    topics: ["FIN"],
    ranking: ["A"],
    note: "Submission fee $75 members / $85 non-members"
  },
  {
    id: "aib2026",
    short: "AIB 2026",
    name: "Academy of International Business Annual Meeting",
    url: "https://www.aib.world/events/annual-meeting/",
    deadline: "2026-01-12",
    conference_start: "2026-06-29",
    conference_end: "2026-07-03",
    location: "Manchester, UK",
    topics: ["IB","MGT","STR"],
    ranking: ["A*","A","B"],
    note: "Rule of THREE: max 3 submissions per person"
  },
  {
    id: "ama2026",
    short: "AMA WMC 2026",
    name: "AMA Winter Marketing Academics Conference",
    url: "https://www.ama.org/events/",
    deadline: "2025-10-15",
    conference_start: "2026-02-18",
    conference_end: "2026-02-21",
    location: "TBA, USA",
    topics: ["MKT"],
    ranking: ["A*","A","B"],
    note: "Multiple AMA conferences per year; check site for updates"
  },
  {
    id: "sfs2026",
    short: "SFS Cavalcade 2026",
    name: "SFS Cavalcade North America",
    url: "https://sfs.org/cavalcade/",
    deadline: "2026-01-15",
    conference_start: "2026-05-20",
    conference_end: "2026-05-22",
    location: "TBA, USA",
    topics: ["FIN"],
    ranking: ["A*"],
    note: "Society for Financial Studies flagship event"
  },
  {
    id: "sms2026",
    short: "SMS 2026",
    name: "Strategic Management Society Annual Conference",
    url: "https://www.strategicmanagement.net/ig/sms-annual-conference",
    deadline: "2026-02-18",
    conference_start: "2026-10-17",
    conference_end: "2026-10-20",
    location: "Berlin, Germany",
    topics: ["STR","MGT"],
    ranking: ["A*","A"],
    note: "Theme: Strategy in a Fragmented Geo-Economic Landscape"
  },
  {
    id: "eaa2026",
    short: "EAA 2026",
    name: "European Accounting Association Annual Congress",
    url: "https://www.eaa-online.org/r/default.asp?iId=HGFHLI",
    deadline: "2025-11-01",
    conference_start: "2026-05-06",
    conference_end: "2026-05-08",
    location: "TBA, Europe",
    topics: ["ACC"],
    ranking: ["A"],
    note: "European accounting community flagship"
  },
  {
    id: "emac2026",
    short: "EMAC 2026",
    name: "European Marketing Academy Annual Conference",
    url: "https://www.emac-online.org/r/default.asp?iId=HHJFIE",
    deadline: "2025-11-15",
    conference_start: "2026-05-26",
    conference_end: "2026-05-29",
    location: "TBA, Europe",
    topics: ["MKT"],
    ranking: ["A*","A","B"],
    note: "Leading European marketing research conference"
  },
  {
    id: "bcerc2026",
    short: "BCERC 2026",
    name: "Babson College Entrepreneurship Research Conference",
    url: "https://www.babson.edu/academics/centers-and-institutes/the-arthur-m-blank-center-for-entrepreneurship/babson-college-entrepreneurship-research-conference/",
    deadline: "2026-01-15",
    conference_start: "2026-06-03",
    conference_end: "2026-06-06",
    location: "TBA",
    topics: ["ENT"],
    ranking: ["A*","A"],
    note: "Oldest dedicated entrepreneurship research conference"
  },
  {
    id: "aaa2026",
    short: "AAA 2026",
    name: "American Academy of Advertising Annual Conference",
    url: "https://aaasite.memberclicks.net/2026-annual-conference",
    deadline: "2025-10-01",
    conference_start: "2026-03-25",
    conference_end: "2026-03-28",
    location: "TBA, USA",
    topics: ["MKT"],
    ranking: ["A","B"],
    note: "Premier advertising academics conference"
  },
  {
    id: "ams2026",
    short: "AMS 2026",
    name: "Academy of Marketing Science Annual Conference",
    url: "https://www.ams-web.org/page/AnnualConference",
    deadline: "2025-11-01",
    conference_start: "2026-05-19",
    conference_end: "2026-05-22",
    location: "TBA",
    topics: ["MKT"],
    ranking: ["A*"],
    note: "JAMS affiliated conference"
  },
  {
    id: "areuea2026",
    short: "AREUEA 2026",
    name: "AREUEA Annual Conference",
    url: "https://www.areuea.org/",
    deadline: "2025-10-01",
    conference_start: "2026-01-03",
    conference_end: "2026-01-05",
    location: "San Francisco, CA, USA",
    topics: ["FIN","RE"],
    ranking: ["A"],
    note: "Held alongside ASSA meetings"
  },
  {
    id: "aria2026",
    short: "ARIA 2026",
    name: "American Risk and Insurance Association Annual Meeting",
    url: "https://www.aria.org/meetings/annual-meeting/",
    deadline: "2026-04-01",
    conference_start: "2026-08-02",
    conference_end: "2026-08-05",
    location: "TBA, USA",
    topics: ["FIN","INS"],
    ranking: ["B"],
    note: "Risk and insurance research community"
  },
  {
    id: "aspa2026",
    short: "ASPA 2026",
    name: "American Society for Public Administration Annual Conference",
    url: "https://www.aspanet.org/",
    deadline: "2025-11-01",
    conference_start: "2026-03-27",
    conference_end: "2026-03-31",
    location: "TBA, USA",
    topics: ["PA"],
    ranking: ["B"],
    note: "Premier public administration conference"
  },
  {
    id: "baa2026",
    short: "BAA 2026",
    name: "British Accounting Association Annual Conference",
    url: "https://www.baa.uk.com/events/annual-conference/",
    deadline: "2026-01-15",
    conference_start: "2026-03-30",
    conference_end: "2026-04-01",
    location: "TBA, UK",
    topics: ["ACC"],
    ranking: ["B"],
    note: "Main UK accounting academic conference"
  },
  {
    id: "bam2026",
    short: "BAM 2026",
    name: "British Academy of Management Annual Conference",
    url: "https://www.bam.ac.uk/events/annual-conference",
    deadline: "2026-03-01",
    conference_start: "2026-09-01",
    conference_end: "2026-09-04",
    location: "TBA, UK",
    topics: ["MGT","OB","HR","STR"],
    ranking: ["B"],
    note: "Leading UK management research conference"
  },
  {
    id: "bhc2026",
    short: "BHC 2026",
    name: "Business History Conference Annual Meeting",
    url: "https://thebhc.org/all-annual-meetings",
    deadline: "2025-10-17",
    conference_start: "2026-03-26",
    conference_end: "2026-03-28",
    location: "London, UK",
    topics: ["HIST","MGT"],
    ranking: ["A","B"],
    note: "Theme: Co-Creation. Imperial College London"
  },
  {
    id: "car2026",
    short: "CAR 2026",
    name: "Contemporary Accounting Research Conference",
    url: "https://caaa.ca/events/car-conference/",
    deadline: "2026-04-01",
    conference_start: "2026-10-08",
    conference_end: "2026-10-10",
    location: "TBA, Canada",
    topics: ["ACC"],
    ranking: ["A*"],
    note: "Canadian accounting research flagship"
  },
  {
    id: "dsi2026",
    short: "DSI 2026",
    name: "Decision Sciences Institute Annual Meeting",
    url: "https://decisionsciences.org/conferences/",
    deadline: "2026-06-01",
    conference_start: "2026-11-21",
    conference_end: "2026-11-23",
    location: "San Francisco, CA, USA",
    topics: ["OPS","DS","MGT"],
    ranking: ["A"],
    note: "Annual flagship for Decision Sciences"
  },
  {
    id: "eawop2027",
    short: "EAWOP 2027",
    name: "EAWOP Work & Organizational Psychology Congress",
    url: "https://eawop.org/",
    deadline: "2026-11-01",
    conference_start: "2027-05-12",
    conference_end: "2027-05-15",
    location: "TBA, Europe",
    topics: ["OB","HR","PSY"],
    ranking: ["B"],
    note: "Biennial congress; next edition 2027"
  },
  {
    id: "efma2026",
    short: "EFMA 2026",
    name: "European Finance Association / EFMA Annual Meeting",
    url: "https://www.efmaefm.org/",
    deadline: "2026-02-01",
    conference_start: "2026-06-24",
    conference_end: "2026-06-27",
    location: "TBA, Europe",
    topics: ["FIN"],
    ranking: ["B"],
    note: "European Financial Management Association"
  },
  {
    id: "egos2026",
    short: "EGOS 2026",
    name: "European Group for Organizational Studies Colloquium",
    url: "https://www.egos.org/",
    deadline: "2026-01-15",
    conference_start: "2026-07-02",
    conference_end: "2026-07-04",
    location: "TBA, Europe",
    topics: ["MGT","OB","STR"],
    ranking: ["A*","A"],
    note: "Sub-theme submissions by January"
  },
  {
    id: "euram2026",
    short: "EURAM 2026",
    name: "European Academy of Management Annual Conference",
    url: "https://www.euram-online.org/",
    deadline: "2026-01-15",
    conference_start: "2026-06-17",
    conference_end: "2026-06-20",
    location: "TBA, Europe",
    topics: ["MGT","STR","OB","HR"],
    ranking: ["B"],
    note: "Pan-European management research conference"
  },
  {
    id: "ica2026",
    short: "ICA 2026",
    name: "International Communication Association Annual Conference",
    url: "https://www.icahdq.org/page/AnnualConference",
    deadline: "2025-11-01",
    conference_start: "2026-05-21",
    conference_end: "2026-05-25",
    location: "TBA",
    topics: ["COMM"],
    ranking: ["B"],
    note: "International communication research"
  },
  {
    id: "icsb2026",
    short: "ICSB 2026",
    name: "International Council for Small Business World Conference",
    url: "https://www.icsb.org/conference/",
    deadline: "2026-02-01",
    conference_start: "2026-06-15",
    conference_end: "2026-06-18",
    location: "TBA",
    topics: ["ENT","SME"],
    ranking: ["A","B"],
    note: "World's oldest SME/entrepreneurship conference"
  },
  {
    id: "ieem2026",
    short: "IEEM 2026",
    name: "IEEE International Conference on Industrial Engineering and Engineering Management",
    url: "https://www.ieem.org/",
    deadline: "2026-07-01",
    conference_start: "2026-12-06",
    conference_end: "2026-12-09",
    location: "TBA, Asia",
    topics: ["TECH","OPS","MGT"],
    ranking: ["A"],
    note: "IEEE engineering management flagship"
  },
  {
    id: "ifera2026",
    short: "IFERA 2026",
    name: "International Family Enterprise Research Academy Annual Conference",
    url: "https://www.ifera.org/",
    deadline: "2026-01-15",
    conference_start: "2026-06-09",
    conference_end: "2026-06-12",
    location: "TBA",
    topics: ["ENT","MGT"],
    ranking: ["B"],
    note: "Leading family business research conference"
  },
  {
    id: "iise2026",
    short: "IISE 2026",
    name: "Institute of Industrial and Systems Engineers Annual Conference",
    url: "https://www.iise.org/Annual/",
    deadline: "2025-11-01",
    conference_start: "2026-05-30",
    conference_end: "2026-06-02",
    location: "TBA, USA",
    topics: ["OPS","TECH"],
    ranking: ["A"],
    note: "Industrial and systems engineering flagship"
  },
  {
    id: "interact2027",
    short: "INTERACT 2027",
    name: "IFIP TC13 International Conference on Human-Computer Interaction",
    url: "https://interact.ifip-tc13.org/",
    deadline: "2026-12-01",
    conference_start: "2027-08-23",
    conference_end: "2027-08-27",
    location: "Tallinn, Estonia",
    topics: ["HCI","TECH","IS"],
    ranking: ["B"],
    note: "Biennial; next edition 2027 in Tallinn"
  },
  {
    id: "ipma2026",
    short: "IPMA 2026",
    name: "International Project Management Association World Congress",
    url: "https://www.ipma.world/events/world-congress/",
    deadline: "2026-04-01",
    conference_start: "2026-09-28",
    conference_end: "2026-10-01",
    location: "TBA",
    topics: ["MGT","OPS"],
    ranking: ["B"],
    note: "World's leading project management congress"
  },
  {
    id: "ipsera2026",
    short: "IPSERA 2026",
    name: "International Purchasing and Supply Education and Research Association Conference",
    url: "https://www.ipsera.com/",
    deadline: "2025-10-01",
    conference_start: "2026-03-22",
    conference_end: "2026-03-25",
    location: "TBA, Europe",
    topics: ["OPS","SCM"],
    ranking: ["A"],
    note: "Purchasing and supply chain management focus"
  },
  {
    id: "isbe2026",
    short: "ISBE 2026",
    name: "Institute for Small Business and Entrepreneurship Annual Conference",
    url: "https://www.isbe.org.uk/",
    deadline: "2026-05-01",
    conference_start: "2026-11-04",
    conference_end: "2026-11-06",
    location: "TBA, UK",
    topics: ["ENT","SME"],
    ranking: ["B"],
    note: "UK's premier SME and entrepreneurship conference"
  },
  {
    id: "sjdm2026",
    short: "SJDM 2026",
    name: "Society for Judgment and Decision Making Annual Conference",
    url: "https://www.sjdm.org/",
    deadline: "2026-06-15",
    conference_start: "2026-11-14",
    conference_end: "2026-11-17",
    location: "TBA",
    topics: ["PSY","MGT","OB"],
    ranking: ["B"],
    note: "Judgment, decision, and behavioural research"
  },
  {
    id: "siop2026",
    short: "SIOP 2026",
    name: "Society for Industrial and Organizational Psychology Annual Conference",
    url: "https://www.siop.org/Annual-Conference/",
    deadline: "2025-06-15",
    conference_start: "2026-04-22",
    conference_end: "2026-04-25",
    location: "TBA, USA",
    topics: ["OB","HR","PSY"],
    ranking: ["B"],
    note: "Premier I-O psychology conference"
  },
  {
    id: "rnd2026",
    short: "R&D Mgmt 2026",
    name: "R&D Management Conference",
    url: "https://www.rnd2026.org/",
    deadline: "2026-02-28",
    conference_start: "2026-06-22",
    conference_end: "2026-06-24",
    location: "Manchester, UK",
    topics: ["TECH","STR","MGT"],
    ranking: ["B"],
    note: "Back to its birthplace at Univ. of Manchester"
  },
  {
    id: "acr2026",
    short: "ACR 2026",
    name: "Association for Consumer Research North American Conference",
    url: "https://www.acrwebsite.org/web/conferences/acr-north-american-conference",
    deadline: "2026-03-15",
    conference_start: "2026-10-08",
    conference_end: "2026-10-11",
    location: "TBA, USA",
    topics: ["MKT","PSY"],
    ranking: ["A*"],
    note: "Premier consumer research conference"
  },
  {
    id: "ila2026",
    short: "ILA 2026",
    name: "International Leadership Association Annual Conference",
    url: "https://ilaglobalnetwork.org/annual-conference/",
    deadline: "2026-04-01",
    conference_start: "2026-10-21",
    conference_end: "2026-10-24",
    location: "TBA",
    topics: ["MGT","OB","HR"],
    ranking: ["A"],
    note: "Leadership Quarterly affiliated conference"
  },
  {
    id: "arnova2026",
    short: "ARNOVA 2026",
    name: "Association for Research on Nonprofit Organizations and Voluntary Action Annual Conference",
    url: "https://arnova.org/conferences/",
    deadline: "2026-05-01",
    conference_start: "2026-11-18",
    conference_end: "2026-11-21",
    location: "TBA, USA",
    topics: ["PA","MGT"],
    ranking: ["B"],
    note: "Nonprofit and voluntary sector research"
  },
  {
    id: "jar2026",
    short: "JAR 2026",
    name: "Journal of Accounting Research Annual Conference",
    url: "https://www.chicagobooth.edu/research/jar/conference",
    deadline: "2026-07-01",
    conference_start: "2026-09-25",
    conference_end: "2026-09-26",
    location: "Chicago, IL, USA",
    topics: ["ACC"],
    ranking: ["A*"],
    note: "Invitation via JAR paper submission process"
  },
  {
    id: "efa2026",
    short: "EFA 2026",
    name: "Eastern Finance Association Annual Meetings",
    url: "https://www.easternfinance.org/",
    deadline: "2025-11-15",
    conference_start: "2026-04-08",
    conference_end: "2026-04-11",
    location: "TBA, USA",
    topics: ["FIN"],
    ranking: ["B"],
    note: "Open to all finance topics"
  },
  {
    id: "scp2026",
    short: "SCP 2026",
    name: "Society for Consumer Psychology Annual Conference",
    url: "https://www.myscp.org/annual-conference.html",
    deadline: "2025-07-15",
    conference_start: "2026-02-26",
    conference_end: "2026-02-28",
    location: "TBA, USA",
    topics: ["MKT","PSY"],
    ranking: ["A*"],
    note: "Premier consumer psychology academic conference"
  },
  {
    id: "ttra2026",
    short: "TTRA 2026",
    name: "Travel and Tourism Research Association Annual Conference",
    url: "https://www.ttra.com/",
    deadline: "2025-11-15",
    conference_start: "2026-06-15",
    conference_end: "2026-06-18",
    location: "TBA",
    topics: ["MKT","MGT"],
    ranking: ["B"],
    note: "Tourism and hospitality research"
  },
  {
    id: "euroma2026",
    short: "EurOMA 2026",
    name: "European Operations Management Association Annual Conference",
    url: "https://euroma-online.org/",
    deadline: "2026-01-15",
    conference_start: "2026-06-28",
    conference_end: "2026-07-01",
    location: "TBA, Europe",
    topics: ["OPS","SCM"],
    ranking: ["A"],
    note: "European operations management community"
  },
  {
    id: "acei2026",
    short: "ACEI 2025",
    name: "Association for Cultural Economics International Conference",
    url: "https://culturaleconomics.org/",
    deadline: "2025-11-01",
    conference_start: "2026-06-22",
    conference_end: "2026-06-25",
    location: "Rotterdam, Netherlands",
    topics: ["ECON","MKT"],
    ranking: ["B"],
    note: "23rd edition; 50 years since ACEI founding"
  },
  {
    id: "shrm2026",
    short: "SHRM 2026",
    name: "SHRM Annual Conference & Expo",
    url: "https://www.shrm.org/conferences-events",
    deadline: "2025-10-15",
    conference_start: "2026-06-21",
    conference_end: "2026-06-24",
    location: "TBA, USA",
    topics: ["HR"],
    ranking: ["A"],
    note: "World's largest HR professional event"
  },
  {
    id: "iarep2026",
    short: "IAREP 2026",
    name: "International Association for Research in Economic Psychology Annual Conference",
    url: "https://www.iarep.org/",
    deadline: "2026-03-01",
    conference_start: "2026-09-09",
    conference_end: "2026-09-12",
    location: "TBA",
    topics: ["PSY","ECON"],
    ranking: ["B"],
    note: "Economic psychology research"
  },
];

// Topic definitions
const TOPICS = {
  ACC:  { label: "Accounting",          color: "#6366f1" },
  COMM: { label: "Communication",       color: "#8b5cf6" },
  DS:   { label: "Data Science",        color: "#0ea5e9" },
  ECON: { label: "Economics",           color: "#f59e0b" },
  ENT:  { label: "Entrepreneurship",    color: "#10b981" },
  FIN:  { label: "Finance",             color: "#3b82f6" },
  HCI:  { label: "Human-Computer Int.", color: "#06b6d4" },
  HIST: { label: "Business History",    color: "#a78bfa" },
  HR:   { label: "Human Resources",     color: "#f97316" },
  IB:   { label: "Int'l Business",      color: "#14b8a6" },
  INS:  { label: "Insurance",           color: "#64748b" },
  IS:   { label: "Information Systems", color: "#2563eb" },
  MGT:  { label: "Management",          color: "#7c3aed" },
  MKT:  { label: "Marketing",           color: "#ec4899" },
  OB:   { label: "Org. Behaviour",      color: "#f43f5e" },
  OPS:  { label: "Operations",          color: "#84cc16" },
  PA:   { label: "Public Admin.",       color: "#6b7280" },
  PSY:  { label: "Psychology",          color: "#a855f7" },
  RE:   { label: "Real Estate",         color: "#78716c" },
  SCM:  { label: "Supply Chain",        color: "#22c55e" },
  SME:  { label: "Small Business",      color: "#f59e0b" },
  STR:  { label: "Strategy",            color: "#1d4ed8" },
  TECH: { label: "Technology Mgmt.",    color: "#0284c7" },
};
